import type { Officer } from '../types/officer.types';

/**
 * Seed / Development Officer Dataset
 * Used for testing simulation mechanics, domain models, and UI views.
 */
export const DEV_OFFICERS: Officer[] = [
  {
    id: 'officer-4011',
    badgeNumber: '4011',
    firstName: 'James',
    lastName: 'Miller',
    callsign: 'P-401',
    biography: 'Steady, seasoned patrol officer known for procedural discipline and calm radio presence.',
    age: 38,
    gender: 'male',
    nationality: 'American',
    rankId: 'officer',
    divisionId: 'patrol',
    divisionHistory: [
      { divisionId: 'patrol', startDate: '2018-03-12', role: 'Patrol Officer' },
    ],
    dutyStatus: 'on_duty',
    shift: 'shift_b',
    yearsOfService: 8,
    attributes: {
      physical: 6,
      mental: 5,
      social: 6,
      discipline: 8,
      composure: 7,
    },
    skills: {
      fitness: 6,
      defensiveTactics: 5,
      firearms: 6,
      investigation: 4,
      observation: 6,
      forensics: 2,
      reportWriting: 7,
      interviewing: 5,
      negotiation: 5,
      leadership: 4,
      driving: 7,
      firstAid: 5,
    },
    traitIds: ['veteran_street_cop', 'evoc_expert'],
  },
  {
    id: 'officer-4012',
    badgeNumber: '4012',
    firstName: 'Linda',
    lastName: 'Chen',
    callsign: 'P-401B',
    biography: 'Sharp second-year patrol officer with strong technical background and rapid situational observation.',
    age: 26,
    gender: 'female',
    nationality: 'American',
    rankId: 'officer',
    divisionId: 'patrol',
    divisionHistory: [
      { divisionId: 'patrol', startDate: '2023-06-01', role: 'Patrol Officer' },
    ],
    dutyStatus: 'on_duty',
    shift: 'shift_b',
    yearsOfService: 3,
    attributes: {
      physical: 6,
      mental: 8,
      social: 6,
      discipline: 7,
      composure: 6,
    },
    skills: {
      fitness: 5,
      defensiveTactics: 4,
      firearms: 5,
      investigation: 6,
      observation: 8,
      forensics: 5,
      reportWriting: 6,
      interviewing: 6,
      negotiation: 6,
      leadership: 4,
      driving: 5,
      firstAid: 4,
    },
    traitIds: ['sharp_investigator'],
  },
  {
    id: 'officer-3104',
    badgeNumber: '3104',
    firstName: 'Marcus',
    lastName: 'Kowalski',
    callsign: 'S-402',
    biography: 'Tough, battle-tested patrol sergeant who leads night shift operations from the frontline cruiser.',
    age: 44,
    gender: 'male',
    nationality: 'American',
    rankId: 'sergeant',
    divisionId: 'patrol',
    divisionHistory: [
      { divisionId: 'patrol', startDate: '2012-01-10', role: 'Patrol Officer' },
      { divisionId: 'traffic', startDate: '2016-04-15', endDate: '2019-08-30', role: 'Accident Reconstruction' },
      { divisionId: 'patrol', startDate: '2019-09-01', role: 'Patrol Sergeant' },
    ],
    dutyStatus: 'on_duty',
    shift: 'shift_b',
    yearsOfService: 14,
    attributes: {
      physical: 7,
      mental: 6,
      social: 7,
      discipline: 8,
      composure: 8,
    },
    skills: {
      fitness: 6,
      defensiveTactics: 7,
      firearms: 7,
      investigation: 5,
      observation: 7,
      forensics: 3,
      reportWriting: 6,
      interviewing: 7,
      negotiation: 6,
      leadership: 8,
      driving: 7,
      firstAid: 6,
    },
    traitIds: ['veteran_street_cop', 'iron_nerves'],
  },
  {
    id: 'officer-2088',
    badgeNumber: '2088',
    firstName: 'Elena',
    lastName: 'Velez',
    callsign: 'D-41',
    biography: 'Tenacious Major Crimes detective who pursues complex homicide syndicates and forensic cold cases.',
    age: 39,
    gender: 'female',
    nationality: 'American',
    rankId: 'det_1',
    divisionId: 'major_crimes',
    divisionHistory: [
      { divisionId: 'patrol', startDate: '2015-02-01', endDate: '2018-05-30', role: 'Patrol Officer' },
      { divisionId: 'homicide', startDate: '2018-06-01', endDate: '2022-11-15', role: 'Detective 3rd & 2nd Class' },
      { divisionId: 'major_crimes', startDate: '2022-11-16', role: 'Lead Detective' },
    ],
    dutyStatus: 'on_call',
    shift: 'shift_a',
    yearsOfService: 11,
    attributes: {
      physical: 5,
      mental: 9,
      social: 7,
      discipline: 7,
      composure: 8,
    },
    skills: {
      fitness: 4,
      defensiveTactics: 5,
      firearms: 6,
      investigation: 9,
      observation: 8,
      forensics: 8,
      reportWriting: 8,
      interviewing: 8,
      negotiation: 7,
      leadership: 6,
      driving: 5,
      firstAid: 4,
    },
    traitIds: ['sharp_investigator', 'empathetic_negotiator'],
  },
  {
    id: 'officer-2092',
    badgeNumber: '2092',
    firstName: 'David',
    lastName: 'Sterling',
    callsign: 'D-42',
    biography: 'Undercover narcotics detective with deep informant networks across the industrial and river sectors.',
    age: 32,
    gender: 'male',
    nationality: 'American',
    rankId: 'det_2',
    divisionId: 'narcotics',
    divisionHistory: [
      { divisionId: 'patrol', startDate: '2020-04-10', endDate: '2023-01-15', role: 'Patrol Officer' },
      { divisionId: 'narcotics', startDate: '2023-01-16', role: 'Narcotics Detective' },
    ],
    dutyStatus: 'off_duty',
    shift: 'shift_a',
    yearsOfService: 6,
    attributes: {
      physical: 7,
      mental: 7,
      social: 8,
      discipline: 5,
      composure: 6,
    },
    skills: {
      fitness: 7,
      defensiveTactics: 6,
      firearms: 7,
      investigation: 7,
      observation: 7,
      forensics: 4,
      reportWriting: 4,
      interviewing: 8,
      negotiation: 8,
      leadership: 4,
      driving: 6,
      firstAid: 5,
    },
    traitIds: ['hot_headed', 'tactical_marksman'],
  },
  {
    id: 'officer-5019',
    badgeNumber: '5019',
    firstName: 'Sarah',
    lastName: 'Hayes',
    callsign: 'L-04',
    biography: 'Day shift precinct lieutenant maintaining administrative compliance, budget oversight, and squad readiness.',
    age: 48,
    gender: 'female',
    nationality: 'American',
    rankId: 'lieutenant',
    divisionId: 'patrol',
    divisionHistory: [
      { divisionId: 'patrol', startDate: '2007-09-01', endDate: '2014-03-31', role: 'Patrol Officer & Sergeant' },
      { divisionId: 'internal_affairs', startDate: '2014-04-01', endDate: '2019-09-30', role: 'IA Investigator' },
      { divisionId: 'patrol', startDate: '2019-10-01', role: 'Watch Commander' },
    ],
    dutyStatus: 'on_duty',
    shift: 'shift_a',
    yearsOfService: 19,
    attributes: {
      physical: 5,
      mental: 8,
      social: 7,
      discipline: 9,
      composure: 8,
    },
    skills: {
      fitness: 4,
      defensiveTactics: 5,
      firearms: 5,
      investigation: 7,
      observation: 7,
      forensics: 5,
      reportWriting: 9,
      interviewing: 7,
      negotiation: 7,
      leadership: 9,
      driving: 6,
      firstAid: 5,
    },
    traitIds: ['methodical_bureaucrat', 'iron_nerves'],
  },
  {
    id: 'officer-1004',
    badgeNumber: '1004',
    firstName: 'Ray',
    lastName: 'Vance',
    callsign: 'K9-04',
    biography: 'K-9 unit handler partnered with Belgian Malinois "Buster", specializing in tracking and contraband detection.',
    age: 31,
    gender: 'male',
    nationality: 'American',
    rankId: 'officer',
    divisionId: 'swat',
    divisionHistory: [
      { divisionId: 'patrol', startDate: '2021-08-01', endDate: '2023-04-30', role: 'Patrol Officer' },
      { divisionId: 'swat', startDate: '2023-05-01', role: 'K9 Tactical Specialist' },
    ],
    dutyStatus: 'on_duty',
    shift: 'shift_b',
    yearsOfService: 5,
    attributes: {
      physical: 8,
      mental: 6,
      social: 5,
      discipline: 8,
      composure: 7,
    },
    skills: {
      fitness: 8,
      defensiveTactics: 7,
      firearms: 6,
      investigation: 5,
      observation: 8,
      forensics: 3,
      reportWriting: 5,
      interviewing: 4,
      negotiation: 4,
      leadership: 5,
      driving: 7,
      firstAid: 6,
    },
    traitIds: ['tactical_marksman'],
  },
  {
    id: 'officer-4081',
    badgeNumber: '4081',
    firstName: 'Tony',
    lastName: 'Diaz',
    callsign: 'P-408',
    biography: 'Energetic patrol driver partnered with Officer Gallagher, skilled in navigating congested urban corridors.',
    age: 28,
    gender: 'male',
    nationality: 'American',
    rankId: 'officer',
    divisionId: 'patrol',
    divisionHistory: [
      { divisionId: 'patrol', startDate: '2022-10-01', role: 'Patrol Officer' },
    ],
    dutyStatus: 'on_duty',
    shift: 'shift_b',
    yearsOfService: 4,
    attributes: {
      physical: 7,
      mental: 5,
      social: 6,
      discipline: 7,
      composure: 6,
    },
    skills: {
      fitness: 7,
      defensiveTactics: 6,
      firearms: 6,
      investigation: 4,
      observation: 6,
      forensics: 2,
      reportWriting: 5,
      interviewing: 5,
      negotiation: 5,
      leadership: 4,
      driving: 8,
      firstAid: 5,
    },
    traitIds: ['evoc_expert'],
  },
  {
    id: 'officer-4082',
    badgeNumber: '4082',
    firstName: 'Sean',
    lastName: 'Gallagher',
    callsign: 'P-411',
    biography: 'Methodical patrol officer with paramedic certification, frequently acting as primary emergency medical responder.',
    age: 35,
    gender: 'male',
    nationality: 'Irish-American',
    rankId: 'officer',
    divisionId: 'patrol',
    divisionHistory: [
      { divisionId: 'patrol', startDate: '2019-01-15', role: 'Patrol Officer' },
    ],
    dutyStatus: 'on_duty',
    shift: 'shift_b',
    yearsOfService: 7,
    attributes: {
      physical: 6,
      mental: 6,
      social: 7,
      discipline: 7,
      composure: 8,
    },
    skills: {
      fitness: 6,
      defensiveTactics: 5,
      firearms: 5,
      investigation: 5,
      observation: 6,
      forensics: 3,
      reportWriting: 6,
      interviewing: 6,
      negotiation: 6,
      leadership: 5,
      driving: 6,
      firstAid: 9,
    },
    traitIds: ['iron_nerves', 'empathetic_negotiator'],
  },
  {
    id: 'officer-9001',
    badgeNumber: '9001',
    firstName: 'Alex',
    lastName: 'Taylor',
    callsign: 'CDT-01',
    biography: 'Eager academy graduate starting probationary field training under Sergeant Kowalski.',
    age: 22,
    gender: 'non_binary',
    nationality: 'American',
    rankId: 'cadet',
    divisionId: 'patrol',
    divisionHistory: [
      { divisionId: 'patrol', startDate: '2026-01-05', role: 'Probationary Cadet' },
    ],
    dutyStatus: 'on_duty',
    shift: 'shift_b',
    yearsOfService: 1,
    attributes: {
      physical: 6,
      mental: 6,
      social: 5,
      discipline: 6,
      composure: 4,
    },
    skills: {
      fitness: 6,
      defensiveTactics: 4,
      firearms: 4,
      investigation: 3,
      observation: 5,
      forensics: 2,
      reportWriting: 4,
      interviewing: 4,
      negotiation: 3,
      leadership: 2,
      driving: 5,
      firstAid: 4,
    },
    traitIds: [],
  },
];
